Repository StratusNetwork/projectares, pull requests merged in 2018-11, with the labels that each got.

#88 Prevent empty buttons from refreshing the inventory.
  PGM/src/main/java/tc/oc/pgm/listeners/InterfaceListener.java
Labels: ready

#87 Prevent flags from dropping as items.
  PGM/src/main/java/tc/oc/pgm/flag/Flag.java
Labels: ready

#84 Fix matchstats displaying wrongly
  PGM/src/main/java/tc/oc/pgm/playerstats/MatchStatsCommand.java
Labels: review

#79 Make map context a soft reference, and keep a persistent context
  PGM/src/main/java/tc/oc/pgm/commands/MapCommands.java
  PGM/src/main/java/tc/oc/pgm/cycle/CycleMatchModule.java
  PGM/src/main/java/tc/oc/pgm/development/MapDevelopmentCommands.java
  PGM/src/main/java/tc/oc/pgm/map/MapDefinition.java
  PGM/src/main/java/tc/oc/pgm/map/MapPersistentContext.java
  PGM/src/main/java/tc/oc/pgm/map/PGMMap.java
  PGM/src/main/java/tc/oc/pgm/match/MatchLoader.java
  PGM/src/main/java/tc/oc/pgm/rotation/RotationState.java
Labels: testing
